# Generated by Django 4.2.20 on 2025-04-05 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_category_remove_product_product_pro_name_b60cd1_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
